# Generated by Django 2.1.3 on 2018-12-17 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('join_date', models.DateField(verbose_name='join_date')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.Department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.Role')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.UserProfile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assign_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
