# Generated by Django 2.1.3 on 2018-12-17 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0002_auto_20181217_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Users',
        ),
    ]
